### ISSUE TITLE
Locate Hiking Trail API

### ISSUE THREAD

**Issue by KenTran801** [KenTran801/Dine-Decider#1]
Recreation.gov API Key: a98dfabb-0307-46fc-a57e-45d4b1891e28

**Comment by spencercreer** [comment]
As a hiker I would like a user friendly application that allows me to find information on hiking trails in the area. I would like to be able to record my hiking and be given awards for specific achievements.

When the user logs in
Then the user is prompted to find trails nearby
When the user searches a trail
Then the user is given information on the hike including trailheads, mileage, elevation, etc.
When the user completes and logs a hike
Then the mileage, elevation and other information is stored
When the user completes several hikes
Then the user is awarded badges and awards
